### ISSUE TITLE
Add in a few additional cuts

### ISSUE THREAD

**Issue by zqhsfz** [mileswu/JetSubstructureTools#5]
Hi,

Thanks a lot for implementing this tool! I notice there might be some kinematics cuts missing:

1) for track-jets, we want to require number of constituents to be at least 2. This should be nearly 100% efficiency, but it is better to have it since occasionally I see some track-jets in derivation with only one constituent. In addition, we require origin vertex of track-jet to be type xAOD::VxType::PriVtx (which I think should be always the case)
2) For muon, we also add |eta|<2.5 during our pre-recommendation study
3) In pre-recommendation study, we use the track-jet ghost associated to the un-groomed jet area (i.e. parent jet of trimmed fat-jet) to do the b-tagging, which can help improve b-tagging efficiency a little bit.

Thanks,
Qi Zeng

**Comment by makagan** [comment]
Hi Qi,

Thanks for pointing these out.  I think these are quite important, especially the last one which can have a major impact on acceptance.

Giordon, is it possible to use the association to the ungroomed parent jet?

Cheers,
Michael

**Comment by kratsg** [comment]
If this is time critical, I can try and add these today.
